CDCgov/data-exchange-upload

tus/file-hooks/metadata-verify/allowed_destination_and_events.json
- allowed_destination_and_events.json
- adding the dex routing target to the dextesting destination id
=> adding dex routing target to testevent

.gitignore, tus/file-hooks/common/proc_stat_controller.py, tus/file-hooks/post-create/docker-build-post-create-bin.sh, tus/file-hooks/post-create/podman-build-post-create-bin.sh, tus/file-hooks/post-create/post-create, tus/file-hooks/post-create/post_create_bin.py, tus/file-hooks/post-create/requirements.txt, tus/file-hooks/post-create/test/post_create_test.py
Introduces the post-create tus hook for facilitating processing status integration.  This hook is called when metadata is valid, and an upload is about to begin (i.e. right after the first post request is sent to the tus server).  The post-create hook will inform PS API of this event by first creating a trace.  This will be the global trace that follows the file through the entire dex process.  Finally, it starts a child span for capturing the tus resumable upload process, under the "dex-upload" stage name.  This span will be stopped in a later hook, when the upload is complete or terminated.
Testing steps:
You can run this python script from within the CDC network, providing dummy data with the following command: 
`python post_create_bin.py -m "{\"meta_destination_id\": \"1234\", …
=> Upload 785/upload trace start

tus/file-hooks/metadata-verify/allowed_destination_and_events.json
- removed routing to edav copy targets in allowed destinations and events json for AIMS CELR CSV files
=> removed copy to edav storage for aims celr csv

upload-processor/BulkFileUploadFunctionApp/BulkFileUploadFunction.cs, upload-processor/BulkFileUploadFunctionApp/BulkFileUploadFunctionApp.csproj, upload-processor/BulkFileUploadFunctionApp/BulkFileUploadFunctionApp.sln, upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs, upload-processor/BulkFileUploadFunctionApp/Model/CopyReport.cs, upload-processor/BulkFileUploadFunctionApp/Model/HealthCheckResponse.cs, upload-processor/BulkFileUploadFunctionApp/Program.cs, upload-processor/BulkFileUploadFunctionApp/Services/FeatureManagementExecutor.cs, upload-processor/BulkFileUploadFunctionApp/Services/IFeatureManagementExecutor.cs, upload-processor/BulkFileUploadFunctionApp/Services/IProcStatClient.cs, upload-processor/BulkFileUploadFunctionApp/Services/ProcStatClient.cs, upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs, upload-processor/BulkFileUploadFunctionApp/Utils/HealthCheckResultUtil.cs, upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionAppTest.csproj, upload-processor/BulkFileUploadFunctionAppTest/HealthCheckFunctionTests.cs, upload-processor/BulkFileUploadFunctionAppTest/ProcStatClientTest.cs, upload-processor/BulkFileUploadFunctionAppTest/utils/MockedHttpMessageHandler.cs
Sends failure reports to PS API when a copy of a file to a destination storage container fails.  To test this, you can update the code on this branch to invalidate one of the edav or routing connection strings.  You can then deploy the code to the dev function app.  Then, you can upload a file, and then query the PS API report endpoint using the file upload ID.  You should see failure reports for the `dex-file-copy` stage.
This PR also introduces a helper utility for handling feature flag checking.
=> Upload 932/ps api copy errors

docs/openapi.yml
Before this the global or default security options for endpoints were unspecified in the documentation.
=> UPLOAD-1027 Add global security stanza to the openapi.yml

tests/integration/kotlin/src/test/kotlin/ProcStat.kt, upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs, upload-processor/BulkFileUploadFunctionApp/Utils/BlobCopyHelper.cs
This effort ultimately turned out to be a failure.  It was discovered that in order to copy a file across storage accounts using a scheduled lease (as opposed to streams), the storage account needs to be publicly accessible, or a SAS token with appropriate privileges is being used.  Neither of these approaches are options for the Upload API as they go against the CDC security policy for Azure storage.
I did, however, find some ways to clean up the code in a marginal amount and wanted to get that reviewed and merged anyway.
=> Upload 1034/file copy consistency

upload-configs/v2/pulsenet-other.json
Updates to the pulsenet v2 sender manifest config
- name change to pulsenet-other.json to align with data stream route nomenclature
- dummy value added to sender id allowed values
- dummy value added to data producer id allowed values
- one state value added to jurisdiction allowed values
- `pulsenet` value added to data stream allowed values
- `other` value added to data stream route allowed values
- copy config target updated to `routing`
=> UPLOAD-1149 pulsenet v2 sender manifest config

upload-configs/v1/ndlp-influenzaVaccination.json
Update to v1 upload config for influenza vaccination to fix the target to edav instead of routing
=> UPLOAD-1242 v1 config target fix influenza vaccination

upload-server/cmd/cli/hooks.go, upload-server/internal/metadata/metadata.go, upload-server/pkg/hooks/prebuilt.go, upload-server/readme.md, upload-server/testing/testing.go
This PR adds a global timestamp field to the sender manifest, which ultimately gets attached to the metadata of the file.  This global timestamp is generated when an upload is being initialized.  It will be used as a global time anchor for searching for uploads across a time range.  It is stored in ISO format in UTC.
=> UPLOAD-1258/global-timestamp

upload-server/cmd/cli/serve.go, upload-server/testing/testing.go
Before this a client that didn't handle 301 redirects well would fail if they used a path like `/files` this change makes it work easily for both.
=> Handle both trailing slash and not for uploads

upload-server/cmd/cli/datastore.go, upload-server/internal/appconfig/appconfig.go
Specifically at the appConfig level. Before this the default wasn't shared between other azure focused code that needed.
=> Set a default for the Azure Container Endpoint

upload-configs/v2/eicr-fhir.json
- Updated eICR Sender Manifest config - removed unneeded supporting metadata fields: meta_ext_filestatus, meta_ext_uploadid, meta_ext_source
=> UPLOAD-1270/eICR Config Updates

upload-configs/v2/celr-csv.json, upload-configs/v2/celr-hl7v2.json
- CELR v2 CSV Config - updated sender id to `APHL`; updated data_producer_id and jurisdiction to be required, but allow any value
- CELR v2 HL7v2 Config - updated sender id to `APHL`; updated data_producer_id and jurisdiction to be required, but allow any value
=> UPLOAD-1272 v2 config updates

upload-configs/v2/eicr-fhir.json
- eICR sender manifest configuration update - remove edav as a destination target for upload router
=> eICR Target Config remove edav routing

upload-configs/v2/nrss-csv.json, upload-configs/v2/nrss-hl7v2.json
- NRSS HL7v2 sender manifest config - updated sender_id to 'APHL', updated data_producer_id and jurisdiction validations to accept any values
- NRSS CSV sender manifest config - updated sender_id to 'APHL', updated data_producer_id and jurisdiction validations to accept any values
=> Upload-1275 NRSS config update

upload-server/cmd/cli/hooks.go, upload-server/internal/metadata/metadata.go, upload-server/internal/metadata/validation/validation.go
Now other aspects, hooks at the moment, can easily access the same logic getting manifest configs. e.g. 
```go
key, _ := metadata.GetConfigIdentifierByVersion(context.TODO, metadata)
c, _ := cache.GetConfig(key)
c.Copy
```
Another eventual improvement can be to move this one level higher into main.go, where it will then be more easily accessible to any component.
=> Structure refactor: extracting manifest fetching for broader use

upload-configs/v1/aims-celr-csv.json, upload-configs/v1/aims-celr-hl7.json, upload-processor/BulkFileUploadFunctionApp/Model/UploadConfig.cs, upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
This patch is to address a potential issue when transitioning senders from v1 to v2 sender manifest definitions.  Currently, we have a limitation where the v1 and v2 config filenames must match.  If they don't, the upload processor will throw an error as it will be unable to find the v2 config file given v1 use case identifiers if the identifiers are different across versions.
Ex:
v1 destination ID is `myprogram` and event type is `superawesomeevent`.  
v2 data stream ID is `mynewprogram` and data stream route is `superroute`.
Given a v1 manifest, the upload processor will look for upload config files named `myprogram-superawesomeevent.json` for both v1 and v2 configs.  This will result in an error.
This patch adds a field to the upload config called `compat_config_filename` that links a …
=> UPLOAD-1341 Support backwards compatible upload config filenames

upload-configs/v1/aims-celr-hl7.json
Fixing the compat config filename value to match the v2 upload config filename for celr hl7.
=> fix compat filename for v2 celr hl7

upload-server/cmd/cli/serve.go, upload-server/internal/handlerdex/handlerdex.go, upload-server/internal/models/consts.go, upload-server/internal/sbhealth/sbhealth.go
Expands the upload service health endpoint to include a check on the PS API service bus report queue, and removes the health check for the PS API HTTP health check endpoint.
Testing steps:
1. Run locally with the SERVICE_BUS_CONNECTION_STR env var set
2. Send an HTTP GET to `http://localhost:8080/health`
3. You should get back a 200 response with a JSON response that looks like this:
```
{
"status": "UP",
"services": [
{
"service": "Azure Service Bus",
"status": "UP",
"health_issue": "None reported"
},
{
"service": "Tus storage",
"status": "UP",
"health_issue": "None reported"
}
]
}
```
=> Upload 1249/server health check service bus

upload-server/cmd/cli/serve.go
Jira: UPLOAD-1388
This changes the startup behavior to use the tusd in-memory locker, if the Redis service is not available. Currently, the server startup will fail.
The Redis health check configuration will be skipped, if Redis is unavailable as well.
The error messaging is also improved.
=> UPLOAD-1388: Default to tusd in-memory locker, if Redis is not available at startup

upload-server/cmd/cli/datastore.go, upload-server/cmd/cli/hooks.go, upload-server/cmd/cli/serve.go, upload-server/internal/appconfig/appconfig.go, upload-server/internal/postprocessing/deliver.go, upload-server/internal/storeaz/azblobclientcheck.go, upload-server/internal/storeaz/azblobclientnew.go, upload-server/testing/cli_test.go
Idea here is to relate registration of file deliverers and registration of health checks on the respected delivery storage targets.  Eg: Registering an EDAV deliverer should also register a health check on the EDAV storage (file or azure).
=> Delivery Connection Resiliance and Health Check

tests/smoke/kotlin/src/test/kotlin/Health.kt, tests/smoke/kotlin/src/test/resources/invalid_manifests_invalid_value.json, tests/smoke/kotlin/src/test/resources/invalid_manifests_required_fields.json, tests/smoke/kotlin/src/test/resources/valid_manifests_v2.json
1. Happy path file is updated with ABCs sender manifest valid fields and allowed values.
2.  Invalid Value error path file is updated with ABCs sender manifest fields, with at least one field containing a value that is not allowed.
3. Invalid Field Exclusion error path file is updated with ABCs sender manifest fields, with at least one required field missing.
=> ABCs - Metadata Smoke Test Additions

upload-server/cmd/main.go
This adds the handling of the `SIGTERM` signal, so that the server can gracefully shutdown when the OS sends a `SIGTERM` broadcast to all processes during a shutdown.
Prior to adding this, the CTRL-c interrupt was handled, but the SIGTERM via a process kill command was not.
From local testing:
- Killing the process during a tusd file upload:
- Immediately stops the process and exits OK.
- Has a partial file size in tus-prefix/ at the point it was stopped.
- After starting up another server, continuing the upload via the client works OK.
- Killing the process during the file delivery:
- The workers successfully copy the full files out to destinations before exiting.
- NOTE: Depending on the file size and the OS's grace period timing (before broadcasting the final SIGKILL), this still might …
=> Add handling for SIGTERM signal for graceful process termination

upload-server/internal/metadata/metadata.go, upload-server/pkg/reports/builder.go
This PR assures that UTC is used for timestamps
=> utc for global timestamp and better format for report start and end time

tests/bad-uploader/examples/test.hl7, tests/bad-uploader/examples/test.json, tests/bad-uploader/go.mod, tests/bad-uploader/go.sum, tests/bad-uploader/main.go, tests/bad-uploader/template.go, tests/bad-uploader/tests/test copy.json
This allows the construction of very large structured files (like a huge hl7v2 file) without a massive impact on system resources.
=> Allow sub templates in the simulator

tests/smoke/kotlin/src/test/resources/invalid_manifests_invalid_value.json, tests/smoke/kotlin/src/test/resources/valid_manifests_v2.json, upload-configs/v2/ed3n-other.json
- Adds an `uploaded_by` required text field to the ed3n-other config.
- Adds the `uploaded_by` field to TESTS json.
=> Update ed3n config w/ uploaded_by field

upload-server/internal/metadata/metadata.go, upload-server/pkg/hooks/prebuilt.go
The purpose of this patch is to provide tus clients with the custom upload ID that the server creates when there are validation errors.  This is to allow these clients to gather PS API report information on that upload attempt more easily.
My initial approach to this was to simply concatenate the upload ID to the validation error message within the response body.  I then thought providing a structured json body with fields for the upload ID and validation errors was better because clients can parse this information out more easily.
=> Upload 1528/upload id in error response

upload-configs/v2/covid-all-monthly-vaccination-csv.json, upload-configs/v2/covid-bridge-vaccination-csv.json, upload-configs/v2/influenza-vaccination-csv.json, upload-configs/v2/routine-immunization-other.json, upload-configs/v2/rsv-prevention-csv.json
- Added test allowed value "XXA" to NDLP sender manifest configurations to be utilized for sender testing purposes
- Allowed values added to data_producer_id and jurisdiction allowed values list
- Configs updated: Covid Bridge Vaccination, Covid All Monthly Vaccination, RSV Prevention, Influenza Vaccination, and Routine Immunization
=> add test config values for sender testing

upload-server/cmd/cli/hooks.go, upload-server/cmd/cli/route.go, upload-server/cmd/cli/serve.go, upload-server/cmd/main.go, upload-server/internal/appconfig/appconfig.go, upload-server/internal/event/publish.go, upload-server/internal/event/subscribe.go, upload-server/internal/metadata/metadata.go, upload-server/internal/postprocessing/deliver.go, upload-server/internal/postprocessing/merge.go, upload-server/internal/postprocessing/postprocessor.go, upload-server/internal/storeaz/blobutil.go, upload-server/internal/upload/report.go, upload-server/pkg/reports/builder.go, upload-server/testing/cli_test.go
Adds a new endpoint at the path `/route/<uuid>` that accepts a post request with the following body:
```
{
"target": "routing" | "edav"
}
```
When this request is received, the service attempts to redeliver the file to the specified target.  It returns a 200 if it was able to find the file and re-issue the delivery operation.  It returns a 400 if the request operation is not POST, the body is malformed, or if the target is not supported.  It returns a 404 if the file is not found.
=> Upload 1580/route endpoint

upload-server/internal/metadata/metadata.go, upload-server/internal/postprocessing/deliver.go, upload-server/testing/cli_test.go
Fixes folder prefix logic to apply logic to edav and routing destinations.  Also tweaks logic to add a folder prefix using the data steam and route.
=> set folder prefix using datastream and route

upload-server/Dockerfile
In response to this Fortify Scan Result: https://cdc-dexops.atlassian.net/browse/UPLOAD-1550
Attempt to fix the `Dockerfile Misconfiguration: Dependency Confusion` by giving a specific version to the `alpine` image
=> Dockerfile update

upload-server/cmd/main.go, upload-server/internal/appconfig/appconfig.go, upload-server/internal/event/event.go, upload-server/internal/event/subscribe.go, upload-server/pkg/reports/builder.go, upload-server/pkg/reports/reports.go
This patch addresses an issue with the in-memory subscriber in which when an error occurred during the handling of an event, the go routine would hang because it would attempt to retry by putting the event back on the channel.  This is an unbuffered channel, so the go routine would block until something read the channel, but this would result in a deadlock because the parent go routine would wait for this go routine to complete before reading the channel again.  
A simple retry mechanism was implemented to mitigate this.  Events now contain a new field that holds a retry count.  When an error occurred during the handling of this event, the process will check if the count is less than some max number.  If that's true, it will put the event back on the channel but in a new go routine.  If …
=> UPLOAD-1647/bugfix-event-handle-error-improvement

upload-server/internal/metadata/metadata.go, upload-server/internal/postprocessing/deliver.go, upload-server/testing/cli_test.go
This patch tweaks the logic for generating the upload file prefix by adding a trailing slash for all files and not just ones with the date prefix.
=> add trailing slash for files with no date prefix

upload-server/internal/metadata/metadata.go, upload-server/testing/cli_test.go
Appends the upload ID to the metadata map.  This was a behavior in the new deprecated upload processor that needs to be replicated to the upload server.  This implementation appends the uid to the metadata in the pre-create step.  That way, when the append operation is executed in the pre-finish step, the uid is already there.
Testing steps:
1. Run the server locally
2. Upload a file
3. Locate the .meta file for the file you uploaded.  It should be located in ./uploads/tus-prefix. The filename will have the same upload ID that was generated.  So if the upload ID is 1234, the .meta file will be 1234.meta
4. In the JSON content within this file, observe that there is a field for `upload_id` with the value of the upload ID for the file you uploaded
=> UPLOAD-1666/bugfix append tuid to metadata

upload-server/internal/ui/assets/demo.js, upload-server/internal/ui/assets/progress.css, upload-server/internal/ui/manifest.tmpl, upload-server/internal/ui/upload.tmpl
To make the UI more accessible, provide a visual representation for the upload process.
To test:
- Run locally and go thru the UI to upload an item
- In order to make the upload longer, change the chunk size to a two or three digit number
=> 1676: Progress Bar for UI

upload-server/internal/metadata/metadata.go, upload-server/internal/metadata/v1/manifest.go, upload-server/testing/testing.go
This patch fixes an issue when uploading files with a v1 manifest that has a non-standard v2 config.  Manifests of this type use a special field in their configs called `CompatConfigFilename` to select the v2 config used to hydrate the file.  An example of a config of this type can be found here: https://github.com/CDCgov/data-exchange-upload/blob/main/upload-configs/v1/aims-celr-csv.json#L77
The server was failing to look in the `v2` subdirectory when fetching configs in this way, resulting in a 404 and the file ultimately not being delivered, and metadata not being appended to it.
This patch addresses this issue by prepending "v2" to the path to the config.  A unit test was also added to cover the case where a manifest of this type is used.
Tickets: …
=> fix 404 when getting compat config file

.github/workflows/build-and-deploy-branch-tst.yml
Created a GHA for this repo that remote triggers "TST - Build and Deploy Branch" GHA in the devops repo. This will make deploying branches to the TST environment easier and prevent copy/paste errors that could happen when you have to manually enter the branch name.
=> created a GHA in the main repo that remote-triggers a test deployment

upload-configs/v2/h5-influenza-vaccination-csv.json
- updated config name to `h5-influenza-vaccination-csv.json`
- updated data_stream_id allowed value to `h5-influenza-vaccination`
- added custom metadata field meta_ext_sourceversion allowed value `V2022-12-31`
- removed all compatible field lines; this config was never a v1 config, so these lines were not needed
- added `XXA` allowed test value to jurisdiction
- added full list of allowed values to data_producer_id
=> update H5 flu vax config

upload-server/internal/ui/index.html, upload-server/internal/ui/ui.go
Small cleanup for using the navbar component within the index.html page.  Needed to split the static handler into one that explicitly handles root and one for the rest of the static assets.  The new explicit root handler simply executes the template for index.html.
=> tidy: use navbar component on index html

upload-configs/v2/ehdi-csv.json, upload-configs/v2/eicr-fhir.json, upload-server/internal/appconfig/appconfig.go, upload-server/internal/delivery/deliver.go, upload-server/internal/metadata/metadata.go
This patch increases the flexibilty of our upload configurations by allowing us to substitute values from environment variables.  This will allow us to configure the template path for delivery destinations on a per-environment level if we so choose.  
For example, if you wanted to follow a template such as `my/destination/subfolder/test/` for lower environments and `my/destination/subfolder/` for prod, you can by setting an environment variable with the template that you want.
This does this by utilizing the `ExpandEnv` function of the golang `os` package.  This function takes a string and looks for placeholder labels and matches them to environment variables.  This is similar to how github action workflow yml files handle their environment and secret substitutions.
=> UPLOAD-1706/use env var expantion for config parsing

upload-configs/v1/ndlp-covidallmonthlyvaccination.json, upload-configs/v1/ndlp-covidbridgevaccination.json, upload-configs/v1/ndlp-genericimmunization.json, upload-configs/v1/ndlp-routineimmunization.json, upload-configs/v1/ndlp-rsvprevention.json, upload-configs/v2/covid-all-monthly-vaccination-csv.json, upload-configs/v2/covid-bridge-vaccination-csv.json, upload-configs/v2/generic-immunization-other.json, upload-configs/v2/influenza-vaccination-csv.json, upload-configs/v2/routine-immunization-other.json, upload-configs/v2/rsv-prevention-csv.json
- v1 ndlp config updates: added "XXA" test allowed value; added new specification allowed value - flu vax, rsv, covid a, covid b, routine immunization
- v2 ndlp config updates: added new specification allowed value - flu vax, rsv, covid a, covid b, routine immunization
- deleted erroneous named config for generic immunization
- v1 ndlp config for generic immunizations
- v2 ndlp config for generic immunizations
=> new ndlp config and allowed spec value

upload-server/internal/appconfig/appconfig.go, upload-server/internal/loaders/s3.go, upload-server/internal/metadata/metadata.go
Adds an app config env var for specifying a folder for the app configs within an S3 bucket.
Also defaults the S3 config loader bucket to the tus bucket, but uses the `DEX_MANIFEST_CONFIG_BUCKET_NAME` env var if it exists.  This allows users to place their upload configs in a separate bucket if they so choose.
=> env var for s3 upload config folder name

.github/workflows/tus-upload-server-ci.yml
github.ref_name resolved to PR number when PR was opened. this change is to resolve to the branch name which is what the fortify workflow requires
=> Updated gh action REF input to pass in correct value

tests/bad-uploader/config.go
- Fixing the validations that bad uploader is doing for the default configuration.  
- Adding in extra download targets for the default.  
- Put the targets in `manifestTargets` that lives close to the `manifest` object to have it a little bit easier to see them both.
=> Fixing the default validations for dextesting/testevent1

upload-server/internal/appconfig/appconfig.go, upload-server/internal/metadata/metadata.go, upload-server/internal/ui/ui.go, upload-server/pkg/azureinspector/azure.go, upload-server/pkg/fileinspector/file.go, upload-server/pkg/fileinspector/status.go, upload-server/pkg/reports/builder.go, upload-server/pkg/s3inspector/s3.go
Update all time formats to include nanosecond precision.
=> #UPLOAD-1826 update all date formats to RFC3339Nano

tests/smoke/kotlin/README.md, tests/smoke/kotlin/local.properties-example, tests/smoke/kotlin/src/test/kotlin/FileCopy.kt, tests/smoke/kotlin/src/test/kotlin/ProcStat.kt, tests/smoke/kotlin/src/test/kotlin/model/FileDelivery.kt, tests/smoke/kotlin/src/test/kotlin/model/InfoResponse.kt, tests/smoke/kotlin/src/test/kotlin/util/ConfigLoader.kt, tests/smoke/kotlin/src/test/kotlin/util/Constants.kt, tests/smoke/kotlin/src/test/kotlin/util/DataProvider.kt, tests/smoke/kotlin/src/test/kotlin/util/EnvConfig.kt, tests/smoke/kotlin/src/test/kotlin/util/Metadata.kt, tests/smoke/kotlin/src/test/resources/valid_manifests_v1.json, tests/smoke/kotlin/src/test/resources/valid_manifests_v2.json
Making the end to end kotlin TestNG tests more cloud agnostic and not rely on cloud services to validate results.  The primary change here is rather than going in to Azure to validate results or collect information to validate against, we will use the /info endpoint of the upload api to validate results against and trust those results there.
Changes:
- Add an environment variable to the local.properties files to name the environment being targeted. 
- Remove connecting to the Azure Blob Service from tests and instead utilize the existing uploadClient to get details from the '/info' endpoint given a UID
- change tests to read from a "test case" with manifest details and other validations rather than just a manifest
- Change assertions to validate from the '/info' endpoint results and make …
=> Upload 1747/cloud agnostic e2e tests

upload-server/internal/appconfig/appconfig.go
This patch is to allow the browser to send requests to the server in a deployed environment.  Currently, the port number that the upload service listens on is also used by the browser to send upload requests to.  This won't work for a deployed environment, when the browser needs to send requests to port 443.  We can tell the browser to send requests to 443 by setting the SERVER_PORT config var, but this causes the service to fail to start because it will listen on 443, which it may not have access to do so, and another service is likely already using this port on the box it is deployed to.
This patch alleviates this conflict by separating the host (and port) that the browser uses from the one that the server listens on.
=> separate config vars for UI server host assignment

upload-server/internal/postprocessing/postprocessor.go
This patch fixes an issue where delivery info for a blob copy report won't get set if there is a delivery failure.  The fix is to simply set the info when the builder for the report is instantiated.
=> set delivery name on builder init

upload-server/cmd/cli/route.go, upload-server/cmd/main_test.go, upload-server/configs/local/deliver.yml, upload-server/configs/testing/azurite_destinations.yml, upload-server/configs/testing/file_destinations.yml, upload-server/configs/testing/mix_destinations.yml, upload-server/configs/testing/s3_destinations.yml, upload-server/internal/delivery/deliver.go, upload-server/internal/delivery/s3.go, upload-server/internal/postprocessing/merge.go, upload-server/internal/postprocessing/postprocessor.go, upload-server/testing/cli_test.go, upload-server/testing/delivery.yml
This is an iteration on the deliver configuration schema.  The goal is to decouple delivery targets from routing groups.  This will improve robustness by preventing possible misconfiguration of creating multiple delivery targets with the same name.  With this, we want to make sure the server fails to start if the deliver yml is misconfiguration in this way.
=> Decouple Delivery Targets From Route Groups

upload-server/cmd/cli/route.go, upload-server/configs/local/deliver.yml, upload-server/configs/testing/azurite_destinations.yml, upload-server/configs/testing/file_destinations.yml, upload-server/configs/testing/mix_destinations.yml, upload-server/configs/testing/s3_destinations.yml, upload-server/internal/delivery/azure.go, upload-server/internal/delivery/deliver.go, upload-server/internal/delivery/delivery_test.go, upload-server/internal/delivery/file.go, upload-server/internal/delivery/s3.go, upload-server/internal/event/event.go, upload-server/internal/metadata/metadata.go, upload-server/internal/postprocessing/merge.go, upload-server/internal/postprocessing/postprocessor.go, upload-server/testing/cli_test.go, upload-server/testing/delivery.yml
before this the current time at delivery was used to construct the destination path. This changes that to use the time the file submission started from the sender.
=> PHDO-87: Use dex_ingest_datetime for file delivery

tests/bad-uploader/config.go
Due to a recent update in the configuration, the dextesting use case will only be delivered to the dex edav target.  This patch updates the load test to reflect that.
=> only expect edav delivery target for dextesing

tests/bad-uploader/config.go, tests/bad-uploader/info.go, tests/bad-uploader/main.go
Adds an optional flag for the upload info endpoint.  This is to cover the case where the info endpoint has the same subpath as the upload endpoint.  This is the case with the public URLs for the Upload API.  The upload endpoint is `https://api.cdc.gov/upload` and the info endpoint is `https://api.cdc.gov/upload/info`.  The script was erroniously checking the info endpoint at `https://api.cdc.gov/info` as it assumed the info endpoint was on a different subpath than the upload endpoint.  However, for the public URLs of the Upload API, that is not the case.
If no value for this new flag is provided, it will default to using the value provided for the `url` flag.
=> flag for info endpoint

tests/bad-uploader/main.go
This patch tells the bad uploader to return a non-zero exit code if upload or validation errors occurred.  This is to help notify CD pipelines that something bad has happened, and the job should ultimately be failed.
=> Bad uploader exit code

upload-server/internal/delivery/azure.go
This patch handles the URL encoding that the Azure blob client does when created.  When given a blob name, the blob client creates a URL property within its instance.  When this happens, the blob name gets URL encoded.  Therefore, when the URL property was used for reporting purposes, it was showing the URL encoded string.  This patch handles this by decoding the URL before returning it to the caller.
=> PHDO-153 Decode destination URL from Azure destinations

upload-configs/ehdi_csv.json, upload-configs/eicr_fhir.json, upload-configs/pulsenet_localsequencefile.json
- Added value `PHDO-USER` to PulseNet config sender-id metadata allowed value list
- Added value `PHDO-USER` to eICR config sender-id metadata allowed value list
- Added value `PHDO-USER` to EHDI config sender-id and data-producer-id metadata allowed value list
- Added value `XX` to EHDI config jurisdiction metadata allowed value list
=> adding test values to data stream configs

upload-server/docs/env-configs.md, upload-server/internal/readme.md, upload-server/readme.md
Adds documentation to the repo's README files to describe the new auth aspect of the system.  Specifically includes:
- New environment variables and configurations
- New behavior of both server and UI
This PR also includes removal of the EICR configuration documentation as that datastream has been offboarded.
=> Phdo 550/auth docs

tests/bad-uploader/auth.go, tests/bad-uploader/config.go, tests/bad-uploader/main.go, tests/bad-uploader/readme.md
- Adds more example commands for testing against deployed upload API
- Logging of upload ID on success and failure
- Logging of token request failure
=> PHDO-593/bad-uploader-doc-improvements

upload-server/cmd/cli/serve.go, upload-server/cmd/cli/setupmetrics.go, upload-server/internal/metrics/uploads.go
This is a quick addition to our prometheus metrics to add a histogram for counting upload speeds in megabytes per second.  This histogram can later be used in grafana/prometheus to show median upload speed in MB/sec.  This will give a good idea of overall upload performance for users of the Upload API.  The higher the speed, the faster files can get uploaded, which likely results in a happier user.
=> Phdo 611/spike upload observability

upload-server/cmd/cli/serve.go, upload-server/cmd/cli/setupmetrics.go, upload-server/configs/local/grafana/provisioning/dashboards/dex.json, upload-server/internal/metrics/uploads.go
Quick patch to improve the accuracy of the median upload speed calculation in prometheus by using finer grained buckets for lower values.  At some point, this should probably be a configurable thing.
This also changes the hook that runs metrics for post processing to the postfinish hook to not interfere with the synchronous response that the upload client gets back when an upload is finished.
Also includes JSON for the grafana dashboard that matches the live environments.
=> PHDO-631/upload-speed-histogram-buckets

upload-server/configs/local/grafana/provisioning/dashboards/dex.json, upload-server/configs/local/prometheus/prometheus.yml, upload-server/configs/local/prometheus/rules.yml
This is a change to the local prometheus and grafana dashboard to include a panel that shows the time since an upload was completed by the upload server.  The prometheus query that is calculating this metric can be broken down as follows:
- Track the positive increases in the `tusd_upload_completed` metric
- Take the timestamp of those occurrences as epoch milliseconds
- Use the "From Now" unit in Grafana to display the timestamp as a human readable "time ago" message
Improvements:
- Use the `upload_manifest_count` metric to group time since by datastream and route. (done)
**Note that when testing this locally, you may need to upload a file a couple times just for the prometheus rule to scrape the upload manifest counter metric.  This is due to the fact that this metric is not initialized …
=> Phdo 676 metric time since last upload

upload-server/configs/local/grafana/provisioning/dashboards/dex.json
Minor patch to refine the PHDO Snapshot Grafana dashboard.
- Update active goroutine threshold: 50,000 for yellow; 75,000 for red; 100,000 for dark red
- Use SUM instead of AVG for active delivery aggregate function
=> Phdo 713/active goroutine thresh

upload-server/cmd/cli/delivery.go, upload-server/cmd/cli/metrics.go, upload-server/configs/local/grafana/provisioning/dashboards/dex.json, upload-server/internal/metrics/delivery.go, upload-server/internal/postprocessing/postprocessor.go, upload-server/testing/cli_test.go
Patch to fix the failed delivery counter not being tracked correctly.  This was due to an inconsistency in the label name that was being incremented, and the one that Grafana was looking for.
=> Phdo 729/bugfix delivery failed metric

upload-server/configs/local/grafana/provisioning/dashboards/dex.json, upload-server/configs/local/prometheus/rules.yml
This patch adds a panel to the snapshot dashboard to show a table for time since last successful delivery for each unique delivery target.  This required a new prometheus rule to be added to pre-calculate the timestamp of the increase in the delivery complete counter.
=> Phdo 683/dashboard time since last delivery

upload-server/configs/local/grafana/provisioning/dashboards/dex.json
Problem: The metric `dex_server_active_uploads` gets frequently out of sync in distributed scenarios where there are multiple replicas of this service.  In these situations, race conditions happen that make the counter report inaccurate values, such as negative values.  In addition, this metric does not take into account uploads that have been abandoned.  In the grafana dashboard gauge, this gives the false impression that an upload is in progress, when really it will never finish.  Overall, this is a consequence of Tusd as it doesn't keep track of uploads that haven't received a chunk after a certain amount of time, or have otherwise gone stale.
Mitigation: To mitigate this, we use a different promQL query that relies on two counters that are already being emitted by Tusd: …
=> PHDO-693 Active Upload Alternative Metric
