CDCgov/data-exchange-upload

.gitignore, .vscode/settings.json, tus/file-hooks/metadata-verify/allowed_destination_and_events.json, tus/file-hooks/metadata-verify/build-pre-create-bin.sh, tus/file-hooks/metadata-verify/ndlp-ri-meta-definition.json, tus/file-hooks/metadata-verify/pre-create, tus/file-hooks/metadata-verify/pre-create-bin.py, tus/file-hooks/metadata-verify/pre-create-bin.spec, tus/python-clients/tus-uploader-local.py, tus/python-clients/tuspy-uploader-local.py, tus/python-clients/tuspy-uploader-test-ndlp-ri-good.py, tus/python-clients/tuspy-uploader-test-ndlp-ri-meta-issue.py, tus/python-clients/tuspy-uploader-test-ndlp-ri-schema-1p1.py, tus/python-clients/tuspy-uploader-test.py
PR to merge the tusd meta hooks for doing metadata verification before upload starts
=> Tusd file hooks meta

.github/workflows/mirror.yml
Github Action workflow to sync this repository with its companion repository in the internal cdc org.
=> mirror workflow

.github/workflows/deploy-rc-staging.yml, .github/workflows/remote-cd-trigger-template.yml
Related PR: https://github.com/cdcent/data-exchange-upload-devops/pull/5
=> Fixed syntax in remote trigger workflow

supplemental-api-function-app/src/main/java/gov/cdc/ocio/supplementalapi/FunctionJavaWrappers.java, supplemental-api-function-app/src/main/kotlin/gov/cdc/ocio/supplementalapi/functions/HealthCheckFunction.kt
https://cdc-dexops.atlassian.net/browse/UPLOAD-423
=> supplemental api health check endpoint

cosmos-sync-function-app/build.gradle, cosmos-sync-function-app/src/main/java/gov/cdc/ocio/cosmossync/FunctionJavaWrappers.java, cosmos-sync-function-app/src/main/kotlin/gov/cdc/ocio/cosmossync/functions/HealthCheckFunction.kt
https://cdc-dexops.atlassian.net/browse/UPLOAD-430
=> 430: implement health check db sync

tus/file-hooks/upload-status/post_receive_bin.py
https://cdc-dexops.atlassian.net/browse/UPLOAD-501
=> ndlp filename metadata issue

.github/workflows/upload-configs.yml
- github workflow for upload-configs
-
-
- can be tested once merged in
- [UPLOAD-521](github workflow for upload-configs)
- Related PR: https://github.com/cdcent/data-exchange-upload-devops/pull/16
[UPLOAD-521]: https://cdc-dexops.atlassian.net/browse/UPLOAD-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added workflow for upload-configs

supplemental-api-function-app/build.gradle, supplemental-api-function-app/src/main/kotlin/gov/cdc/ocio/supplementalapi/cosmos/CosmosClientManager.kt, supplemental-api-function-app/src/main/kotlin/gov/cdc/ocio/supplementalapi/functions/FunctionKotlinWrappers.kt, supplemental-api-function-app/src/main/kotlin/gov/cdc/ocio/supplementalapi/functions/HealthCheckFunction.kt, supplemental-api-function-app/src/test/kotlin/test/HealthCheckFunctionTest.kt
- Implement unit test for supplemental api using TestNG
=> upload-498 implement unit test for supplemental api

BulkFileUploadFunctionApp/BulkFileUploadFunctionApp.csproj, BulkFileUploadFunctionApp/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionAppTest.csproj, BulkFileUploadFunctionApp/BulkFileUploadFunctionAppTest/HealthCheckFunctionTests.cs, BulkFileUploadFunctionApp/BulkFileUploadFunctionAppTest/Usings.cs, BulkFileUploadFunctionApp/HealthCheckFunction.cs
=> upload-497 unit test for bulk upload

BulkFileUploadFunctionApp/BulkFileUploadFunction.cs
[UPLOAD-649](https://cdc-dexops.atlassian.net/browse/UPLOAD-649)
[UPLOAD-649]: https://cdc-dexops.atlassian.net/browse/UPLOAD-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated log level from error to information

BulkFileUploadFunctionApp/BulkFileUploadFunction.cs, BulkFileUploadFunctionApp/BulkFileUploadFunctionApp.csproj, BulkFileUploadFunctionApp/Program.cs, BulkFileUploadFunctionApp/host.json
- Integrate App Insight SDK for tracing support.
- https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service
=> upload-555 integrate app insight

supplemental-api-function-app/build.gradle
- sup api dependency upgraded from azure-cosmos:4.41.0 to azure-cosmos:4.42.0
=> sup api dependecy update

tus/file-hooks/metadata-verify/allowed_destination_and_events.json, tus/file-hooks/metadata-verify/definitions/daart_hl7_meta_definition.json
https://cdc-dexops.atlassian.net/browse/UPLOAD-730
=> daart config changes

BulkFileUploadFunctionApp/BulkFileUploadFunction.cs, BulkFileUploadFunctionApp/BulkFileUploadFunctionApp.csproj, BulkFileUploadFunctionApp/Program.cs
- Create json logger for bulk upload api
=> upload-563 create json logger for bulk upload api

BulkFileUploadFunctionApp/BulkFileUploadFunction.cs, BulkFileUploadFunctionApp/BulkFileUploadFunctionApp.csproj, BulkFileUploadFunctionApp/Program.cs
- Add feature flag for routing changes.
=> upload-885 add feature flag for routing changes

tus/file-hooks/upload-status/post_receive_bin.py
https://cdc-dexops.atlassian.net/browse/UPLOAD-746
=> UPLOAD-746: adding message envelop

upload-processor/BulkFileUploadFunctionApp/BulkFileUploadFunction.cs, upload-processor/BulkFileUploadFunctionAppTest/BulkFileUploadFunctionAppTest.sln
Simply removes the code for sending a file's metadata to NDLP.
=> UPLOAD-942/remove call to metadata relay

CHANGELOG.md, docs/Release Notes/DEX Upload Release Notes - Version 1.2.3.md
please review release notes 1.2.3
=> UPLOAD-939/new markdown for release notes 1.2.3

docs/Release Notes/DEX Upload Release Notes - Version 1.2.3.md
- Minor formatting revisions to release notes for v1.2.3 - removing spaces, formatting a url
=> release notes v1.2.3 minor formatting revisions

docs/Release Notes/DEX Upload Release Notes - Version 1.2.3.md
- fixing embedded link in v1.2.3 release notes
=> fixing release notes embedded link

tus/file-hooks/metadata-verify/definitions/daart_hl7_meta_definition.json, upload-configs/daart-hl7.json
- DAART Upload-configs file, initial version to facilitate testing
=> initial version DAART upload-configs file

.github/workflows/deploy-rc-tst.yml, .github/workflows/remote-cd-trigger-template.yml, .github/workflows/tus-hooks-ci-template.yml, .github/workflows/tus-post-create-hook-ci.yml, .github/workflows/tus-post-create-hook-dev.yml, .github/workflows/tus-post-finish-hook-ci.yml, .github/workflows/tus-post-finish-hook-remote-cd-dev.yml, .github/workflows/tus-post-receive-hook-ci.yml, .github/workflows/tus-post-receive-hook-remote-cd-dev.yml, .github/workflows/tus-pre-create-hook-ci.yml, .github/workflows/tus-pre-create-hook-remote-cd-dev.yml, .github/workflows/upload-configs-cd-dev.yml, .github/workflows/upload-processor-ci.yml, .github/workflows/upload-processor-dev.yml
- TST environment pipeline
- 
- Renamed workflows for better organization
-
- [upload-776](https://cdc-dexops.atlassian.net/browse/UPLOAD-776)
- Related PR: https://github.com/cdcent/data-exchange-upload-devops/pull/42
=> Renamed files and workflow titles

.github/workflows/upload-processor-ci.yml
=> upload-948 add ci unit test

upload-processor/BulkFileUploadFunctionApp/HealthCheckFunction.cs
- Change duration time format.
=> upload-969 time format change

upload-configs/v2/aims-celr-hl7.json
Fixing compat field names for aims-celr-hl7 for v2 metadata
=> fix compat field names

upload-processor/BulkFileUploadFunctionApp/Model/MetadataReport.cs, upload-processor/BulkFileUploadFunctionApp/Services/IProcStatClient.cs, upload-processor/BulkFileUploadFunctionApp/Services/ProcStatClient.cs, upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs, upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs
Creates a new report to be sent to PS API for file metadata.
=> UPLOAD-1069/create report for metadata

upload-processor/BulkFileUploadFunctionApp/Services/UploadProcessingService.cs
This field name change is requested by PS API team, and will be deployed as a patch in v1.4.1
=> use parent_span_id instead of span_id

tus/file-hooks/metadata-verify/pre_create_bin.py, tus/file-hooks/metadata-verify/test/test_get_filename_from_metadata.py
- Check invalid characters in filename metadata fields
=> upload-1101- Check invalid characters in filename metadata fields

tus/file-hooks/metadata-verify/pre_create_bin.py
=> upload-1101 bug fix

tus/file-hooks/metadata-verify/pre_create_bin.py, tus/file-hooks/metadata-verify/requirements.txt, tus/file-hooks/post-create/post_create_bin.py, tus/file-hooks/post-create/requirements.txt, tus/file-hooks/post-create/test/test_post_create.py, tus/file-hooks/post-finish/post_finish_bin.py, tus/file-hooks/post-finish/requirements.txt, upload-processor/BulkFileUploadFunctionApp/Utils/Constants.cs
- Implement feature fjagging for ps api in tus hooks
=> upload-1114 implement feature flagging

upload-configs/v2/ehdi-csv.json
Updates to ehdi-csv.json to align with org data model hierarchy and naming convention
- sender id values updated: replaced underscores with dashes and replaced DOH reference with EHDI reference
- data producer id values updated: replaced underscores with dashes and replaced DOH reference with EHDI reference
=> ehdi config value updates

upload-configs/v2/nrss-csv.json, upload-configs/v2/nrss-hl7v2.json
Updates
- nrss-csv.json: updated sender id to a dummy test value, updated data producer id values replacing underscores with dashes
- nrss-hl7v2.json: updated filename to include data stream route nomenclature, updated data stream route allowed value, updated data producer id value replacing underscores with dashes, updated sender id value, and added supporting metadata fields
=> UPLOAD-1210 NRSS data stream config updates

docs/Release Notes/DEX Upload Release Notes - Version 1.5.0.md
=> UPLOAD-1013 v1.5.0 release notes

docs/Release Notes/DEX Upload Release Notes - Version 1.6.2.md
- DEX Upload API release notes v1.6.2
=> UPLOAD-1259 v1.6.2 release notes

upload-configs/v2/eicr-fhir.json
- eICR v2 sender manifest configuration file - initial config file for testing
=> UPLOAD-1257 eICR v2 sender manifest config initial file

upload-server/internal/handlertusd/handlertusd.go
CORS seems to default to a reasonable config
https://github.com/tus/tusd/blob/main/pkg/handler/config.go#L133
=> Defaulting to respect forwarded headers

docs/Release Notes/DEX Upload Release Notes - Version 1.6.3.md
=> Version 1.6.3 release notes

upload-server/internal/metadata/metadata.go, upload-server/testing/cli_test.go
- Bug fix for PS API report missing fields.
=> upload-1302  bug fix for PS API report missing fields

upload-configs/v1/pulsenet-LocalSequenceFile.json, upload-configs/v2/pulsenet-localsequencefile.json
- filename update to account for revised data stream route value to `pulsenet-localsequencefile.json`
- updated data stream route value to `localsequencefile`
- updated sender id to accept any value
- updated data producer id to accept any value
- updated jurisdiction to accept any value
- updated target to `edav`
- updated folder structure to `root`
- updated folder structure to `root`
=> UPLOAD-1274/ pulsenet config update

upload-configs/v2/pulsenet-localsequencefile.json
- updated v2 config file name to all lower case `pulsenet-localsequencefile.json`
- updated v2 config file to reference v1 compatible fields instead of allowed values
=> Upload 1324/pn config fix

upload-server/clean.sh, upload-server/cmd/cli/hooks.go, upload-server/internal/metadata/metadata.go, upload-server/internal/models/psreport.go, upload-server/internal/models/reports.go, upload-server/testing/cli_test.go, upload-server/testing/testing.go
This sends two new reports to the PS API: Upload started and upload completed.  The upload started report is sent in the post-create hook, and the upload completed report is sent the post-finish hook.
=> Upload 1200/report improvements

upload-server/pkg/redislocker/redislocker.go, upload-server/pkg/redislocker/redislocker_test.go
Also sends fewer release requests
=> Use 2 channels per lock for exchange

upload-configs/v1/ndlp-rsvprevention.json
Fix field name from "schema_version" to "version"
=> fix version field name

upload-configs/v2/abcs-csv.json
- v2 Sender Manifest Upload Configuration file - ABCs Data Stream
=> ABCs data stream upload config

upload-server/internal/appconfig/appconfig.go, upload-server/internal/storeaz/azblobclientnew.go, upload-server/internal/storeaz/blobutil.go
Check env vars from OS for service principle creds instead of app conf object.
=> fix check for service principle

upload-configs/v2/ed3n-other.json
- updated ED3N config: custom metadata field names, allowed values addition for custom metadata field, allowed value updates for sender id, data producer id, and jurisdiction
=> ED3N sender manifest config update

CHANGELOG.md, docs/Release Notes/DEX Upload Release Notes - Version 2.1.2.md
- Upload v2.1.2 release notes
- Changelog update to include v2.1.2
=> v2.1.2 release notes and changelog upd

upload-configs/v2/abcs-csv.json
- ABCs sender manifest configuration updates to include sender id, data producer id, and jurisdiction updates
=> ABCs sender manifest config update

upload-configs/v2/pulsenet-localsequencefile.json
- PulseNet v2 sender manifest configuration updates: add sender id allowed value, add data stream id allowed value, add data stream route allowed value
=> PulseNet v2 config update

upload-configs/v2/pulsenet-localsequencefile.json
- Pulsenet config - updated to include brackets for explicit allowed values
=> PN config fix to add brackets

tests/smoke/kotlin/src/test/kotlin/Health.kt
Added Health check dependencies for Redis locker service
=> Smoke tests - Automate Health check dependencies for Redis service

tests/bad-uploader/main.go
Allows a manifest to be specified as:
- A commandline flag
- In a test case file
- Within test cases files in a directory
Files in a test case directory will be cycled through in round robin.
A test case file also specifies desired size for the file and chunk size for the upload
=> Specify custom manifests in simulation harness

tests/bad-uploader/go.mod, tests/bad-uploader/go.sum, tests/bad-uploader/main.go, tests/bad-uploader/template.go
This allows the simulator to use templates to generate files of any size. It also includes two template functions for generating a random string or a random int.
=> Generating simulation files from a template

CHANGELOG.md, docs/Release Notes/DEX Upload Release Notes - Version 2.2.3.md
- updated changelog.md file with v2.2.3 release details
- v2.2.3 release notes
=> Version 2.2.3 release notes and changelog updates

thanks.md
=> remove thanks.md file

tests/smoke/playwright/playwright.config.ts, upload-server/cmd/cli/serve.go, upload-server/cmd/main.go, upload-server/docker-compose.yml, upload-server/internal/ui/ui.go, upload-server/pkg/redislocker/redislocker.go
- fixed an issue with the docker-compose file
- updated the error message when the Redis locker fails to initialize
- added a Ping to the new Redis locker function so that the connection is checked on start up and start up fails if the service is down.
=> UPLOAD-1662 resolving issues with Redis health check

upload-server/internal/ui/assets/demo.js, upload-server/internal/ui/index.html, upload-server/internal/ui/manifest.tmpl, upload-server/internal/ui/upload.tmpl
fixed issue with upload template, added the icons on every page so that it stops complaining about the favicon
=> fixing issue with upload template

upload-configs/v2/eicr-fhir.json, upload-server/internal/appconfig/appconfig.go, upload-server/internal/delivery/deliver.go
Registers a new target for the eicr destination.
=> UPLOAD-1706/eicr-delivery

docs/openapi.yml
- replaced contact information with Erik K.
- added field level information for the manifest property
- added deliveries property and field information
=> info endpoint swagger updates

upload-server/internal/metadata/v1/manifest.go
Small patch to fix the reports that get generated for manifest hydration.
=> Bugfix: Manifest Hydration Reports

upload-configs/v1/ndlp-genericimmunization.json, upload-configs/v2/generic-immunization-csv.json
- updated compat_config_filename to `generic-immunization-csv.json`
- updated filename to `generic-immunization-csv.json`
- updated copy_config target to `ncird`
- updated data_stream_route allowed value to `csv`
=> generic immunization config updates

upload-configs/v2/generic-immunization-csv.json
Sets path template for generic immunization files.
=> path tmpl for generic immune

CHANGELOG.md
- added sections and bullets for v2.4.1 and v2.5.0 production releases
=> v2.4.1 and v2.5.0 updates

README.md
- updated intro
- updated services section
- updated repository contents
- updated future improvements
- other minor formatting fixes
=> Upload 1757 root readme

upload-server/internal/delivery/deliver.go
We may be able to go a bit further here, allowing us to remove the registration of targets step
=> Simplify unmarshalling

upload-configs/v2/covid-all-monthly-vaccination_csv.json, upload-configs/v2/generic-immunization_csv.json, upload-configs/v2/influenza-vaccination_csv.json, upload-configs/v2/routine-immunization_other.json, upload-configs/v2/rsv-prevention_csv.json
- influenza-vaccination_csv.json
- covid-all-monthly-vaccination_csv.json
- generic-immunization_csv.json
- routine-immunization_other.json
- rsv-prevention_csv.json
=> ncird config allowed value update

upload-server/configs/local/deliver.yml
Updates path_templates to include the rest of the data streams
=> fixup path_templates

.github/workflows/e2e-tests.yml
removed unnecessary quotes around commit_msg
=> UPLOAD-1825/small-tweak

tests/bad-uploader/tests/actual-datastreams/test-covid-all-monthly-vaccination-csv.json, tests/bad-uploader/tests/actual-datastreams/test-ehdi-csv.json, tests/bad-uploader/tests/actual-datastreams/test-eicr-fhir.json, tests/bad-uploader/tests/actual-datastreams/test-generic-immunization-csv.json, tests/bad-uploader/tests/actual-datastreams/test-influenza-vaccination-csv.json, tests/bad-uploader/tests/actual-datastreams/test-pulsenet-localsequencefile.json, tests/bad-uploader/tests/actual-datastreams/test-routine-immunization-other.json, tests/bad-uploader/tests/actual-datastreams/test-rsv-prevention-csv.json, tests/bad-uploader/tests/test-default-largefile.json, tests/bad-uploader/tests/test-default-mediumfile.json, tests/bad-uploader/tests/test-default.json
Added JSON test cases for bad uploader.
- default cases are for dextesting/testevent1
- folder exists for actual data streams, one test case per data stream
=> Adding test files for bad uploader

upload-configs/README.md, upload-configs/sender-manifest.2.0.0.schema.json
Updates
- updated upload-configs readme to remove all v1 references, remove version references, and cleanup of text and formatting
- updated the sender manifest schema definition json to remove version references
=> config readme updates

CHANGELOG.md, docs/Release Notes/PHDO Upload Release Notes - Version 2.6.4.md
- v2.6.4 release notes
- changelog updates for v2.6.4
=> v2.6.4 release notes and changelog update

upload-server/configs/local/grafana/provisioning/dashboards/dex.json, upload-server/configs/local/prometheus/prometheus.yml, upload-server/configs/local/prometheus/rules.yml
Quick fixup to add the `sum by` aggregation to the rule.
=> Phdo 676/metric time since last upload

README.md
- root level README update for minor revisions: typo correction, sections added for upload-scripts and upload-reports subdirectories, added section for bad uploader
=> root folder README minor revisions

README.md, reupload-tool-go/README.md, tests/bad-uploader/readme.md, tests/smoke/README.md, tests/smoke/kotlin/README.md, tests/smoke/playwright/README.md, tests/smoke/playwright/resources/mock-auth-server/README.md, upload-configs/README.md, upload-reports/README.md, upload-scripts/README.md, upload-server/internal/readme.md, upload-server/readme.md
Updates include grammar and type-o fixes, minor rewording
- root readme
- upload-server readme
- upload-config readme
- upload-reports readme
- reupload-tool readme
- bad-uploader readme
- kotlin readme
- playwright readme
=> Phdo 779/doc review
